Core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from Core.views import index,blog,Sitemap


app_name = 'Core'

sitemaps = {
    'sitemap': Sitemap,
}

urlpatterns = [
    path('',view=index,name='index'),
    path('/blog',view=blog,name='blog'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

News/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path('',include('Core.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)),]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Core/models.py
from django.db import models

# Create your models here.

Core/views.py
import datetime
from django.contrib.auth.decorators import login_required
from .utils import email_html
from django.shortcuts import  render,redirect,get_object_or_404
from django.core.paginator import Paginator
import os
from django.conf import settings
from django.http import HttpResponse
from django.views.decorators.cache import cache_page

from django.contrib import sitemaps

from django.http import FileResponse,JsonResponse
from django.contrib import messages
from django.contrib.messages import constants
import logging

logger = logging.getLogger('MyApp')


def index(request):
     return render(request,'index.html')

def blog(request):
     return render(request,'blog.html')

def formulario(request):
    if request.method =="POST":
        email = request.POST.get('email')
        valida = Email.objects.filter(email=email)
        if valida.exists():
            messages.add_message(request, constants.ERROR, 'Email Ja cadastrado')
            logger.info(f'Email Ja cadastrado {email} '+str(datetime.datetime.now())+' horas!')
            return redirect("/")
        cadastrar = Email.objects.create(
            email=email
        )
        cadastrar.save()
        messages.add_message(request, constants.SUCCESS, 'Cadastrado com sucesso')
        return redirect("/")
    
def unsubscriber(request,id):
    email = Email.objects.get(id=id)
    email.ativo =False
    email.save()
    return HttpResponse('Cancelado sua Inscriçao')

@login_required(login_url='/admin/login/?next=/admin/') 
def enviar_emeil(request):
    try:
        path_template = os.path.join(settings.BASE_DIR, 'Core/templates/emails/email.html')
        base_url = request.build_absolute_uri('/')
        emails = Email.objects.filter(ativo=True).all()
        posts = Imagem.objects.only('nome','descricao').filter(destaque=True).all().order_by('-id')[:15]

        for email in emails:
            email_html(path_template, 'Novos Desenhos', [email,],posts=posts,email=email,base_url=base_url)
            messages.add_message(request, constants.SUCCESS, 'Emais enviados com sucesso')
            return redirect("/")
        
    except Exception as msg:
        messages.add_message(request, constants.ERROR, f'Nao foi possivel enviar os Emails consulte o arquivo de Log')
        logger.critical(f'{msg} '+str(datetime.datetime.now())+' horas!')
        return redirect("/")



class Sitemap(sitemaps.Sitemap):
    i18n = True
    changefreq ='monthly'
    priority = 0.7

    def items(self):
        return Imagem.objects.all()        

    def lastmod(self, obj):
        return obj.data_upload

Core/templates/blog.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block 'title' %}
{% trans "Blog" %}
{% endblock %}
{% block 'body' %}
<div class="container-fluid">
    <div class="row justify-content-center">

        <div class="card mb-3 carde" style="max-width: 540px;">
            <div class="row no-gutters">
              <div class="col-md-4">
                <img src="..." alt="...">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title">Card title</h5>
                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                  <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
              </div>
            </div>
          </div>
          
          <div class="card mb-3 carde" style="max-width: 540px;">
            <div class="row no-gutters">
              <div class="col-md-4">
                <img src="..." alt="...">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title">Card title</h5>
                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                  <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
              </div>
            </div>
          </div>
          
          <div class="card mb-3 carde" style="max-width: 540px;">
            <div class="row no-gutters">
              <div class="col-md-4">
                <img src="..." alt="...">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title">Card title</h5>
                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                  <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
              </div>
            </div>
          </div>

          <div class="card mb-3 carde" style="max-width: 540px;">
            <div class="row no-gutters">
              <div class="col-md-4">
                <img src="..." alt="...">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title">Card title</h5>
                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                  <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
              </div>
            </div>
          </div>

    </div>
    <br>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
          
          <li class="page-item"><a class="page-link" href="?page=1">{% trans "Voltar" %}</a></li>
       
          <li class="page-item"><a class="page-link" href="#">0:3</a></li>
        
          <li class="page-item"><a class="page-link" href="?page=2">{% trans "Proximo" %}</a></li>
     
        </ul>
      </nav>
</div>
 {% endblock %}

Core/templates/index.html
{% load i18n %}
{% load static %}
{% block 'body' %}
<title>Pagina Inicial</title>
<div class="newsletter-form">
    <h2>Assine nossa Newsletter</h2>
    <form action="#" method="post">
        {% csrf_token %}
        <input type="email" name="email" placeholder="Seu e-mail" required>
        <br>
        <input type="submit" value="Inscrever-se">
    </form>
    <a href="{% url 'Core:blog' %}">blog</a>
</div>
<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        flex-direction: column;
    }
    .newsletter-form {
        text-align: center;
    }
    .newsletter-form input[type="email"] {
        padding: 10px;
        margin-bottom: 10px;
        width: 300px;
        border-radius: 5px;
        border: 1px solid #ccc;
        font-size: 16px;
    }
    .newsletter-form input[type="submit"] {
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }
    .newsletter-form input[type="submit"]:hover {
        background-color: #0056b3;
    }
</style>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="#">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property="og:title" content="Mundo Colorido Kids" />
    <meta property="og:type" content="website" />
    <meta property="og:image" content="#" />
    <meta property="og:url" content="." />
    <meta property="og:site_name" content="Mundo Colorido Kids" />
    <meta property="og:description"
          content="Explore o mundo colorido da criatividade com desenhos para colorir do Mundo Colorido Kids. Deixe as crianças expressarem sua imaginação com nossa vasta coleção de desenhos divertidos e educativos." />
    <meta name="Title"
          content="Mundo Colorido Kids" />
          <meta name="Author" content="Vitor Gomes" />
          <meta name="description"
                content="Explore o mundo colorido da criatividade com desenhos para colorir do Mundo Colorido Kids. Deixe as crianças expressarem sua imaginação com nossa vasta coleção de desenhos divertidos e educativos.">
          <meta name="KeyWords"
                content="desenhos para colorir, crianças, atividades infantis, educação, criatividade, diversão, aprendizado" />
          <meta name="generator" content="Microsoft FrontPage 5.0" />
          <meta name="Language" CONTENT="Portuguese" />
          <meta name="Rating" CONTENT="Safe For Kids" />
          <meta name="Doc-class" CONTENT="Completed" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link href="{% static 'css/css.css' %}" rel="stylesheet" />
    <title>        
        {% block 'title' %}
        {% endblock %}
</title>
<nav class="navbar navbar-expand-lg navbar-color" style="color:var(--azul-celeste)">
  <a class="navbar-brand" href="#">
    <img src="/docs/4.6/assets/brand/bootstrap-solid.svg" width="30" height="30" alt="">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"><img width="48" height="48" src="https://img.icons8.com/fluency/48/menu--v1.png" alt="menu--v1" /></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
              <a class="nav-link" href="#">Home<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                  Categorias
              </a>
              <div class="dropdown-menu">

                  <a class="dropdown-item" href="#">Categoria <span class="badge badge-danger">categoria</span></a>

              </div>
          </li>

          <li class="nav-item">
              <a class="nav-link" href="#">Sobre Nós</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="#">Contato</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="#">Política de Privacidade</a>
          </li>
      </ul>
  </div>
</nav>
  </head>
  <body>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="text-center alert {{message.tags}}">
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
    </div>

    {% block 'body' %}
	{% endblock %}

  <!-- Footer -->
<footer class="bg-body-tertiary text-center">
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a data-mdb-ripple-init class="btn btn-outline btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a data-mdb-ripple-init class="btn btn-outline btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a data-mdb-ripple-init class="btn btn-outline btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a data-mdb-ripple-init class="btn btn-outline btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a data-mdb-ripple-init class="btn btn-outline btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>

      <!-- Github -->
      <a data-mdb-ripple-init class="btn btn-outline btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
    <!-- Section: Form -->

    <!-- Section: Text -->
    <section class="mb-4">
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt distinctio earum
        repellat quaerat voluptatibus placeat nam, commodi optio pariatur est quia magnam eum
        harum corrupti dicta, aliquam sequi voluptate quas.
      </p>
    </section>
    <!-- Section: Text -->

    <!-- Section: Links -->
    <section class="">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a class="text-body" href="#!">Link 1</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 2</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 3</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 4</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a class="text-body" href="#!">Link 1</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 2</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 3</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 4</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a class="text-body" href="#!">Link 1</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 2</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 3</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 4</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a class="text-body" href="#!">Link 1</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 2</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 3</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 4</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </section>
    <!-- Section: Links -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color:var(--azul-celeste);">
    © 2020 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
  </body>
</html>